"""Internal ability catalog for registered local/runtime tool actions.

The catalog describes existing registered actions as AbilityManifest entries.
It does not register handlers, execute tools, or bypass the existing tool.invoke
runtime authority.
"""

from __future__ import annotations

from backend.services.abilities.manifest import AbilityManifest, AbilityRiskLevel
from backend.services.tools.schemas import SideEffectClass

ACTION_RESULT_SCHEMA_REF = "backend.services.tools.schemas.ActionResult"

INTERNAL_ABILITY_MANIFESTS: tuple[AbilityManifest, ...] = (
    AbilityManifest(
        ability_id="calendar-create-event",
        display_name="Calendar Create Event",
        action_name="calendar.create_event",
        provider="local_calendar",
        capability_name="calendar",
        capability_version="1",
        adapter_name="local-calendar",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.CalendarCreateEventInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.INTERNAL_WRITE,
        risk_level=AbilityRiskLevel.MEDIUM,
        required_permissions=[],
        required_tools=[],
        approval_required=True,
        idempotency_required=False,
        evidence_required=True,
        readback_required=True,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="calendar-read",
        display_name="Calendar Read",
        action_name="calendar.read",
        provider="local_calendar",
        capability_name="calendar",
        capability_version="1",
        adapter_name="local-calendar",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.CalendarReadInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.NONE,
        risk_level=AbilityRiskLevel.LOW,
        required_permissions=[],
        required_tools=[],
        approval_required=False,
        idempotency_required=False,
        evidence_required=True,
        readback_required=False,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="http-request",
        display_name="HTTP Request",
        action_name="http.request",
        provider="httpx",
        capability_name="http",
        capability_version="1",
        adapter_name="httpx",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.HttpRequestInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.EXTERNAL_READ,
        max_side_effect_class=SideEffectClass.EXTERNAL_WRITE,
        resolver_side_effect_classes=(SideEffectClass.EXTERNAL_READ, SideEffectClass.EXTERNAL_WRITE),
        risk_level=AbilityRiskLevel.HIGH,
        required_permissions=[],
        required_tools=[],
        approval_required=True,
        idempotency_required=True,
        evidence_required=True,
        readback_required=False,
        readback_deferred_reason=(
            "HTTP response evidence is captured, but durable external-state readback depends "
            "on the target service and is deferred to provider-specific adapters."
        ),
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="record-read",
        display_name="Record Read",
        action_name="record.read",
        provider="local_records",
        capability_name="records",
        capability_version="1",
        adapter_name="local-records",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.RecordReadInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.NONE,
        risk_level=AbilityRiskLevel.LOW,
        required_permissions=[],
        required_tools=[],
        approval_required=False,
        idempotency_required=False,
        evidence_required=True,
        readback_required=False,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="record-search",
        display_name="Record Search",
        action_name="record.search",
        provider="local_records",
        capability_name="records",
        capability_version="1",
        adapter_name="local-records",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.RecordSearchInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.NONE,
        risk_level=AbilityRiskLevel.LOW,
        required_permissions=[],
        required_tools=[],
        approval_required=False,
        idempotency_required=False,
        evidence_required=True,
        readback_required=False,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="record-write",
        display_name="Record Write",
        action_name="record.write",
        provider="local_records",
        capability_name="records",
        capability_version="1",
        adapter_name="local-records",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.RecordWriteInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.INTERNAL_WRITE,
        risk_level=AbilityRiskLevel.MEDIUM,
        required_permissions=[],
        required_tools=[],
        approval_required=True,
        idempotency_required=False,
        evidence_required=True,
        readback_required=True,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="sales-create-followup-task",
        display_name="Sales Create Followup Task",
        action_name="sales.create_followup_task",
        provider="local_sales",
        capability_name="sales",
        capability_version="1",
        adapter_name="local-sales",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.RecordWriteInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.INTERNAL_WRITE,
        risk_level=AbilityRiskLevel.MEDIUM,
        required_permissions=[],
        required_tools=[],
        approval_required=True,
        idempotency_required=False,
        evidence_required=True,
        readback_required=True,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="sales-draft-followup",
        display_name="Sales Draft Followup",
        action_name="sales.draft_followup",
        provider="local_sales",
        capability_name="sales",
        capability_version="1",
        adapter_name="local-sales",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.FollowupDraftInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.NONE,
        risk_level=AbilityRiskLevel.LOW,
        required_permissions=[],
        required_tools=[],
        approval_required=False,
        idempotency_required=False,
        evidence_required=True,
        readback_required=False,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="sales-log-activity",
        display_name="Sales Log Activity",
        action_name="sales.log_activity",
        provider="local_sales",
        capability_name="sales",
        capability_version="1",
        adapter_name="local-sales",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.RecordWriteInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.INTERNAL_WRITE,
        risk_level=AbilityRiskLevel.MEDIUM,
        required_permissions=[],
        required_tools=[],
        approval_required=True,
        idempotency_required=False,
        evidence_required=True,
        readback_required=True,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="sales-qualify",
        display_name="Sales Qualify",
        action_name="sales.qualify",
        provider="local_sales",
        capability_name="sales",
        capability_version="1",
        adapter_name="local-sales",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.SalesLeadInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.NONE,
        risk_level=AbilityRiskLevel.LOW,
        required_permissions=[],
        required_tools=[],
        approval_required=False,
        idempotency_required=False,
        evidence_required=True,
        readback_required=False,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="sales-recommend-next-action",
        display_name="Sales Recommend Next Action",
        action_name="sales.recommend_next_action",
        provider="local_sales",
        capability_name="sales",
        capability_version="1",
        adapter_name="local-sales",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.SalesLeadInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.NONE,
        risk_level=AbilityRiskLevel.LOW,
        required_permissions=[],
        required_tools=[],
        approval_required=False,
        idempotency_required=False,
        evidence_required=True,
        readback_required=False,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="sales-research",
        display_name="Sales Research",
        action_name="sales.research",
        provider="local_sales",
        capability_name="sales",
        capability_version="1",
        adapter_name="local-sales",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.SalesLeadInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.NONE,
        risk_level=AbilityRiskLevel.LOW,
        required_permissions=[],
        required_tools=[],
        approval_required=False,
        idempotency_required=False,
        evidence_required=True,
        readback_required=False,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="sales-score-lead",
        display_name="Sales Score Lead",
        action_name="sales.score_lead",
        provider="local_sales",
        capability_name="sales",
        capability_version="1",
        adapter_name="local-sales",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.SalesLeadInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.NONE,
        risk_level=AbilityRiskLevel.LOW,
        required_permissions=[],
        required_tools=[],
        approval_required=False,
        idempotency_required=False,
        evidence_required=True,
        readback_required=False,
        enabled_by_default=False,
    ),
    AbilityManifest(
        ability_id="webhook-dispatch",
        display_name="Webhook Dispatch",
        action_name="webhook.dispatch",
        provider="WebhookDispatchService",
        capability_name="webhook",
        capability_version="1",
        adapter_name="webhook-dispatch-service",
        adapter_version="1",
        input_schema_ref="backend.services.tools.schemas.WebhookDispatchInput",
        output_schema_ref=ACTION_RESULT_SCHEMA_REF,
        side_effect_class=SideEffectClass.EXTERNAL_SEND,
        risk_level=AbilityRiskLevel.HIGH,
        required_permissions=[],
        required_tools=[],
        approval_required=True,
        idempotency_required=True,
        evidence_required=True,
        readback_required=False,
        readback_deferred_reason=(
            "Webhook delivery records are captured as dispatch evidence; recipient-side external "
            "readback is deferred to provider-specific verification."
        ),
        enabled_by_default=False,
    ),
)

ABILITY_MANIFESTS_BY_ACTION: dict[str, AbilityManifest] = {
    manifest.action_name: manifest for manifest in INTERNAL_ABILITY_MANIFESTS
}
