apiVersion: v1
kind: Service
metadata:
  name: ajenda-frontend
  namespace: ajenda
  labels:
    app: ajenda-ai
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: ajenda-ai
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http