apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ajenda-api
  namespace: ajenda
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ajenda.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ajenda-api
                port:
                  number: 80
