apiVersion: batch/v1
kind: Job
metadata:
  name: ajenda-migrate
  namespace: ajenda
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ajenda/migrate:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ajenda-config
            - secretRef:
                name: ajenda-secrets
