#!/usr/bin/env bash
# Configure Stripe test-mode credentials for local staging.
# - Creates Ajenda Pro test price when STRIPE_SECRET_KEY is a real sk_test_* key
# - Generates a local webhook signing secret for simulated webhook proof
# - Prints next steps for manual checkout (Stripe CLI) vs automated proof
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${AJENDA_STAGING_ENV_FILE:-$ROOT_DIR/deploy/compose/.env.staging}"
RUNTIME_ENV="${AJENDA_RUNTIME_ENV_FILE:-$ROOT_DIR/deploy/compose/.env.prod}"

log() {
  printf '[stripe-staging-bootstrap] %s\n' "$*"
}

fail() {
  printf '[stripe-staging-bootstrap] ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

[[ -f "$ENV_FILE" ]] || fail "missing env file: $ENV_FILE (copy from deploy/compose/.env.staging.example)"

require_command python3

log "bootstrapping Stripe staging values in $ENV_FILE"

export ENV_FILE RUNTIME_ENV ROOT_DIR
python3 - <<'PY'
from __future__ import annotations

import os
import re
import secrets
from pathlib import Path

import stripe

from backend.billing.staging_proof_helpers import (
    _LOCAL_STAGING_PRICE_PRO,
    _LOCAL_STAGING_PRICE_STARTER,
    is_local_staging_price_id,
    is_placeholder_stripe_value,
    stripe_checkout_ready,
    stripe_webhook_proof_ready,
)

env_path = Path(os.environ["ENV_FILE"])
runtime_path = Path(os.environ["RUNTIME_ENV"])
text = env_path.read_text(encoding="utf-8")


def read_env_value(key: str) -> str | None:
    match = re.search(rf"^{re.escape(key)}=(.*)$", text, flags=re.MULTILINE)
    if not match:
        return None
    return match.group(1).strip()


def upsert_env_value(key: str, value: str) -> None:
    global text
    line = f"{key}={value}"
    pattern = rf"^{re.escape(key)}=.*$"
    if re.search(pattern, text, flags=re.MULTILINE):
        text = re.sub(pattern, line, text, count=1, flags=re.MULTILINE)
    else:
        if not text.endswith("\n"):
            text += "\n"
        text += f"\n# Stripe test mode (generated by stripe-staging-bootstrap.sh)\n{line}\n"


secret_key = read_env_value("STRIPE_SECRET_KEY")
publishable = read_env_value("STRIPE_PUBLISHABLE_KEY")
webhook_secret = read_env_value("STRIPE_WEBHOOK_SECRET")
price_pro = read_env_value("STRIPE_PRICE_PRO")
price_starter = read_env_value("STRIPE_PRICE_STARTER")

changed = False

if is_placeholder_stripe_value(webhook_secret):
    webhook_secret = f"whsec_local_staging_{secrets.token_urlsafe(24)}"
    upsert_env_value("STRIPE_WEBHOOK_SECRET", webhook_secret)
    changed = True
    print(f"generated local webhook secret for simulated proof: {webhook_secret}")

if is_placeholder_stripe_value(secret_key):
    if is_placeholder_stripe_value(price_pro):
        upsert_env_value("STRIPE_PRICE_PRO", _LOCAL_STAGING_PRICE_PRO)
        price_pro = _LOCAL_STAGING_PRICE_PRO
        changed = True
        print(f"set local simulated Pro price id: {price_pro}")

    if is_placeholder_stripe_value(price_starter):
        upsert_env_value("STRIPE_PRICE_STARTER", _LOCAL_STAGING_PRICE_STARTER)
        changed = True
        print(f"set local simulated Starter price id: {_LOCAL_STAGING_PRICE_STARTER}")
else:
    needs_pro = is_placeholder_stripe_value(price_pro) or is_local_staging_price_id(price_pro)
    needs_starter = is_placeholder_stripe_value(price_starter) or is_local_staging_price_id(price_starter)

if is_placeholder_stripe_value(secret_key):
    print(
        "STRIPE_SECRET_KEY is still a placeholder.\n"
        "1. Open https://dashboard.stripe.com/test/apikeys\n"
        "2. Copy the Secret key (sk_test_…)\n"
        "3. Set STRIPE_SECRET_KEY and STRIPE_PUBLISHABLE_KEY in "
        f"{env_path}\n"
        "4. Re-run this script to create test prices automatically."
    )
else:
    stripe.api_key = secret_key
    product = None
    for item in stripe.Product.list(active=True, limit=20).auto_paging_iter():
        if item.get("name") == "Ajenda Pro (Staging)":
            product = item
            break
    if product is None:
        product = stripe.Product.create(name="Ajenda Pro (Staging)", metadata={"ajenda_plan": "pro"})
        print(f"created Stripe product {product['id']}")

    if needs_pro:
        price = stripe.Price.create(
            product=product["id"],
            unit_amount=4900,
            currency="usd",
            recurring={"interval": "month"},
            metadata={"ajenda_plan": "pro"},
        )
        price_pro = price["id"]
        upsert_env_value("STRIPE_PRICE_PRO", price_pro)
        changed = True
        print(f"created Stripe Pro price: {price_pro}")

    if needs_starter:
        starter_product = None
        for item in stripe.Product.list(active=True, limit=20).auto_paging_iter():
            if item.get("name") == "Ajenda Starter (Staging)":
                starter_product = item
                break
        if starter_product is None:
            starter_product = stripe.Product.create(
                name="Ajenda Starter (Staging)",
                metadata={"ajenda_plan": "starter"},
            )
        starter_price = stripe.Price.create(
            product=starter_product["id"],
            unit_amount=1900,
            currency="usd",
            recurring={"interval": "month"},
            metadata={"ajenda_plan": "starter"},
        )
        upsert_env_value("STRIPE_PRICE_STARTER", starter_price["id"])
        changed = True
        print(f"created Stripe Starter price: {starter_price['id']}")

if changed:
    env_path.write_text(text, encoding="utf-8")
    runtime_path.write_text(text, encoding="utf-8")
    print(f"updated {env_path} and synced {runtime_path}")
else:
    print("no env changes required")

webhook_ready = stripe_webhook_proof_ready(
    webhook_secret=read_env_value("STRIPE_WEBHOOK_SECRET"),
    price_pro=read_env_value("STRIPE_PRICE_PRO"),
)
checkout_ready = stripe_checkout_ready(
    secret_key=read_env_value("STRIPE_SECRET_KEY"),
    price_pro=read_env_value("STRIPE_PRICE_PRO"),
)
print("stripe_webhook_proof_ready=", webhook_ready)
print("stripe_checkout_ready=", checkout_ready)
PY

log "next steps:"
log "  1. If STRIPE_SECRET_KEY was updated manually, re-run this script."
log "  2. Restart API: docker compose --env-file deploy/compose/.env.prod -f deploy/compose/docker-compose.prod.yml up -d api --force-recreate"
log "  3. Automated billing proof (simulated webhook): bash deploy/scripts/stripe-billing-staging-proof.sh"
log "  4. Manual UI checkout: run 'stripe listen --forward-to localhost:8000/v1/billing/webhook/stripe' and copy its whsec into STRIPE_WEBHOOK_SECRET, then restart api"