"""Business ontology contracts.

Slice 1 — identities and commercial spine (BusinessObjectType / Ref).
Slice 2 — commercial state: Goal, KPI, BusinessStateSnapshot, BusinessEvent.
Evaluation Intelligence — EvaluationResult and deterministic assessors.
Outcome Intelligence — OutcomeEvaluation and evaluate_outcome delta.
Decision Feedback Intelligence — DecisionSnapshot, effectiveness, learning signal.

Does not execute tools, persist records, or wire composition/runtime.
"""

from backend.services.ontology.commercial_state import (
    COMMERCIAL_RELATIONSHIP_SPECS,
    COMMERCIAL_STATE_SCHEMA_VERSION,
    BusinessEvent,
    BusinessStateSnapshot,
    Goal,
    GoalStatus,
    Kpi,
    KpiDirection,
)
from backend.services.ontology.decision_feedback import (
    DECISION_FEEDBACK_SCHEMA_VERSION,
    ConfidenceCalibrationAssessment,
    ConfidenceCalibrationStatus,
    ConsequenceInventory,
    DecisionEffectivenessEvaluation,
    DecisionEffectivenessStatus,
    DecisionExecutionObservation,
    DecisionFeedbackResult,
    DecisionLearningSignal,
    DecisionQualityAssessment,
    DecisionQualityStatus,
    DecisionSnapshot,
    EffectivenessDimensions,
    ExecutionFidelity,
    LearningSignalStrength,
    assess_confidence_calibration,
    assess_decision_effectiveness,
    assess_decision_quality,
    evaluate_decision_feedback,
    extract_decision_learning_signal,
    inventory_consequences,
    validate_decision_feedback_inputs,
)
from backend.services.ontology.evaluation import (
    EVALUATION_SCHEMA_VERSION,
    EvaluationResult,
    GapKind,
    GoalProgressStatus,
    KpiEvaluation,
    ProgressGap,
    StateAttributeChange,
    StateComparison,
    compare_state_snapshots,
    evaluate_goal_progress,
    evaluate_kpi,
)
from backend.services.ontology.experience_intelligence import (
    EXPERIENCE_INTELLIGENCE_SCHEMA_VERSION,
    ComparabilityStatus,
    ExperienceComparison,
    ExperienceContextSignature,
    ExperienceEpisodeInput,
    ExperienceIntelligenceResult,
    ExperiencePatternCandidate,
    IndependenceStatus,
    RecurrenceAssessment,
    RecurrenceStrength,
    derive_context_signature,
    evaluate_experience_set,
)
from backend.services.ontology.observation_attribution import (
    OBSERVATION_ATTRIBUTION_SCHEMA_VERSION,
    AttributionAssessmentEvidence,
    AttributionEvidenceInput,
    AttributionOrdering,
    ObservationTimeProvenance,
    ObservationTiming,
    evaluate_attribution_evidence,
    resolve_observation_timing,
)
from backend.services.ontology.outcome import (
    OUTCOME_SCHEMA_VERSION,
    AttributionAssessment,
    CriteriaResult,
    DirectionAssessment,
    KpiOutcomeDelta,
    ObservedOutcome,
    OutcomeEvaluation,
    OutcomeExpectation,
    OutcomeStatus,
    evaluate_outcome,
)
from backend.services.ontology.types import (
    BUSINESS_OBJECT_SCHEMA_VERSION,
    CANONICAL_BUSINESS_OBJECT_TYPES,
    OBJECT_TYPE_ALIASES,
    RELATIONSHIP_SPECS,
    BusinessObjectRef,
    BusinessObjectType,
    OntologyRelationshipSpec,
    RelationshipSpec,
    canonicalize_object_type,
    is_canonical_object_type,
)

__all__ = [
    "BUSINESS_OBJECT_SCHEMA_VERSION",
    "CANONICAL_BUSINESS_OBJECT_TYPES",
    "COMMERCIAL_RELATIONSHIP_SPECS",
    "COMMERCIAL_STATE_SCHEMA_VERSION",
    "DECISION_FEEDBACK_SCHEMA_VERSION",
    "EVALUATION_SCHEMA_VERSION",
    "EXPERIENCE_INTELLIGENCE_SCHEMA_VERSION",
    "OBJECT_TYPE_ALIASES",
    "OBSERVATION_ATTRIBUTION_SCHEMA_VERSION",
    "OUTCOME_SCHEMA_VERSION",
    "RELATIONSHIP_SPECS",
    "AttributionAssessment",
    "AttributionAssessmentEvidence",
    "AttributionEvidenceInput",
    "AttributionOrdering",
    "BusinessEvent",
    "BusinessObjectRef",
    "BusinessObjectType",
    "BusinessStateSnapshot",
    "ComparabilityStatus",
    "ConfidenceCalibrationAssessment",
    "ConfidenceCalibrationStatus",
    "ConsequenceInventory",
    "CriteriaResult",
    "DecisionEffectivenessEvaluation",
    "DecisionEffectivenessStatus",
    "DecisionExecutionObservation",
    "DecisionFeedbackResult",
    "DecisionLearningSignal",
    "DecisionQualityAssessment",
    "DecisionQualityStatus",
    "DecisionSnapshot",
    "DirectionAssessment",
    "EffectivenessDimensions",
    "EvaluationResult",
    "ExecutionFidelity",
    "ExperienceComparison",
    "ExperienceContextSignature",
    "ExperienceEpisodeInput",
    "ExperienceIntelligenceResult",
    "ExperiencePatternCandidate",
    "GapKind",
    "Goal",
    "GoalProgressStatus",
    "GoalStatus",
    "IndependenceStatus",
    "Kpi",
    "KpiDirection",
    "KpiEvaluation",
    "KpiOutcomeDelta",
    "LearningSignalStrength",
    "ObservationTimeProvenance",
    "ObservationTiming",
    "ObservedOutcome",
    "OntologyRelationshipSpec",
    "OutcomeEvaluation",
    "OutcomeExpectation",
    "OutcomeStatus",
    "ProgressGap",
    "RecurrenceAssessment",
    "RecurrenceStrength",
    "RelationshipSpec",
    "StateAttributeChange",
    "StateComparison",
    "assess_confidence_calibration",
    "assess_decision_effectiveness",
    "assess_decision_quality",
    "canonicalize_object_type",
    "compare_state_snapshots",
    "derive_context_signature",
    "evaluate_attribution_evidence",
    "evaluate_decision_feedback",
    "evaluate_experience_set",
    "evaluate_goal_progress",
    "evaluate_kpi",
    "evaluate_outcome",
    "extract_decision_learning_signal",
    "inventory_consequences",
    "is_canonical_object_type",
    "resolve_observation_timing",
    "validate_decision_feedback_inputs",
]
