#!/usr/bin/env python3
"""Refresh and export opt-in live E2E plugin tokens to ~/.ajenda/e2e.env.

UI-first provider setup (recommended for Salesforce, LinkedIn, Gmail, etc.):
  Connect providers in Ajenda Credentials UI; tokens stay tenant-scoped in the DB.

This script is for opt-in live E2E lanes only. It loads ~/.ajenda/google-cli.env and
~/.ajenda/salesforce-cli.env (when present) so CLI OAuth clients can refresh local
token files, then exports refreshed secrets to ~/.ajenda/e2e.env for pytest/deploy
proof scripts. Prefer Credentials UI for product tenants; use provider_oauth_bridge
register only when bridging CLI tokens into a dev tenant.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AJENDA_DIR = Path.home() / ".ajenda"
OUTPUT_PATH = AJENDA_DIR / "e2e.env"
GOOGLE_ENV = AJENDA_DIR / "google-cli.env"
SALESFORCE_ENV = AJENDA_DIR / "salesforce-cli.env"


def _load_shell_exports(path: Path) -> None:
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or not line.startswith("export "):
            continue
        key, _, value = line.removeprefix("export ").partition("=")
        if key and value:
            os.environ[key] = value.strip("'\"")


def _write_exports(exports: dict[str, str]) -> None:
    AJENDA_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/generate_e2e_tokens.py — do not commit.",
        "# Usage: set -a && source ~/.ajenda/e2e.env && set +a",
        "",
    ]
    for key in sorted(exports):
        value = exports[key]
        if not value:
            continue
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'export {key}="{escaped}"')
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUTPUT_PATH.chmod(0o600)


def _status(label: str, ok: bool, detail: str) -> None:
    mark = "ok" if ok else "missing"
    print(f"[{mark}] {label}: {detail}")


def main() -> int:
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))

    _load_shell_exports(GOOGLE_ENV)
    _load_shell_exports(SALESFORCE_ENV)
    exports: dict[str, str] = {}
    missing: list[str] = []

    # Gmail (refresh via stored refresh_token)
    try:
        from backend.services.tools.google_oauth_cli import resolve_gmail_access_token

        gmail_token = resolve_gmail_access_token()
        if gmail_token:
            exports["AJENDA_E2E_GMAIL_TOKEN"] = gmail_token
            _status("Gmail", True, "access token refreshed")
        else:
            missing.append("Gmail — run: python scripts/google/gmail_cli_auth.py auth")
            _status("Gmail", False, "no token in ~/.ajenda/google-oauth.yml")
    except Exception as exc:
        missing.append(f"Gmail — {exc}")
        _status("Gmail", False, str(exc))

    # Google Calendar (separate file or shared yaml with calendar scope)
    try:
        from tests.integration.standalone.google_calendar_e2e_support import (
            resolve_google_calendar_credential_secret_for_e2e,
        )

        calendar_secret = resolve_google_calendar_credential_secret_for_e2e()
        if calendar_secret:
            exports["AJENDA_E2E_GOOGLE_CALENDAR_SECRET"] = calendar_secret
            _status("Google Calendar", True, "credential secret resolved")
        else:
            missing.append(
                "Google Calendar — run: python scripts/google/gmail_cli_auth.py calendar-auth"
            )
            _status("Google Calendar", False, "no calendar-scoped token")
    except Exception as exc:
        missing.append(f"Google Calendar — {exc}")
        _status("Google Calendar", False, str(exc))

    # HubSpot (HubSpot CLI config)
    try:
        from tests.integration.standalone.hubspot_e2e_support import resolve_hubspot_access_token

        hubspot = resolve_hubspot_access_token()
        if hubspot:
            exports["AJENDA_E2E_HUBSPOT_PAK"] = hubspot
            _status("HubSpot", True, "token from ~/.hscli/config.yml")
        else:
            missing.append("HubSpot — run: hs account auth")
            _status("HubSpot", False, "no HubSpot CLI token")
    except Exception as exc:
        missing.append(f"HubSpot — {exc}")
        _status("HubSpot", False, str(exc))

    # GitHub (GitHub CLI)
    try:
        from tests.integration.standalone.github_e2e_support import (
            DEFAULT_GITHUB_OAUTH_CONFIG_PATH,
            resolve_github_credential_secret_for_e2e,
        )

        existing = resolve_github_credential_secret_for_e2e()
        if not existing:
            proc = subprocess.run(["gh", "auth", "token"], capture_output=True, text=True, check=False)
            if proc.returncode == 0 and proc.stdout.strip():
                token = proc.stdout.strip()
                payload = {
                    "provider_kind": "github",
                    "access_token": token,
                    "scopes": ["repo", "read:user"],
                    "token_type": "bearer",
                }
                DEFAULT_GITHUB_OAUTH_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
                DEFAULT_GITHUB_OAUTH_CONFIG_PATH.write_text(
                    json.dumps(payload, indent=2, sort_keys=True) + "\n",
                    encoding="utf-8",
                )
                DEFAULT_GITHUB_OAUTH_CONFIG_PATH.chmod(0o600)
                existing = json.dumps(payload, sort_keys=True)
        if existing:
            exports["AJENDA_E2E_GITHUB_SECRET"] = existing
            _status("GitHub", True, f"stored at {DEFAULT_GITHUB_OAUTH_CONFIG_PATH}")
        else:
            missing.append("GitHub — run: gh auth login")
            _status("GitHub", False, "no gh token")
    except Exception as exc:
        missing.append(f"GitHub — {exc}")
        _status("GitHub", False, str(exc))

    # LinkedIn / Salesforce — UI-first; CLI bridge optional for live E2E
    for label, env_key, path, hint in (
        (
            "LinkedIn",
            "AJENDA_E2E_LINKEDIN_TOKEN",
            AJENDA_DIR / "linkedin-oauth.json",
            "Connect LinkedIn in Credentials UI (recommended) or set AJENDA_LINKEDIN_CLIENT_ID/SECRET",
        ),
        (
            "Salesforce",
            "AJENDA_E2E_SALESFORCE_SECRET",
            AJENDA_DIR / "salesforce-oauth.json",
            "Connect Salesforce in Credentials UI (recommended) or: "
            "salesforce-cli.env + salesforce_cli_auth.py auth + provider_oauth_bridge register",
        ),
    ):
        try:
            if env_key in os.environ and os.environ[env_key].strip():
                exports[env_key] = os.environ[env_key].strip()
                _status(label, True, f"from environment {env_key}")
                continue
            if path.is_file() and path.read_text(encoding="utf-8").strip():
                exports[env_key] = path.read_text(encoding="utf-8").strip()
                _status(label, True, f"from {path}")
                continue
            missing.append(f"{label} — {hint}")
            _status(label, False, "not configured")
        except Exception as exc:
            missing.append(f"{label} — {exc}")
            _status(label, False, str(exc))

    _write_exports(exports)
    print(f"\nWrote {len(exports)} export(s) to {OUTPUT_PATH}")
    print("Load before live E2E: set -a && source ~/.ajenda/e2e.env && set +a")

    if missing:
        print("\nStill needed for full plugin live proof:")
        for item in missing:
            print(f"  - {item}")
        return 0 if exports else 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())