#!/usr/bin/env bash
# Write frontend/.env.local with dev tenant + API key for /dev console preloads.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FRONTEND_ENV="${AJENDA_FRONTEND_ENV_FILE:-$ROOT_DIR/frontend/.env.local}"
MASTER_FILE="${AJENDA_FRONTEND_MASTER_FILE:-$HOME/.ajenda/frontend.env}"
TENANT_ID="${AJENDA_DEV_TENANT_ID:-a25c9d83-9096-478a-b178-aeccf3ba7be1}"
COMPOSE_FILE="${AJENDA_PROOF_COMPOSE_FILE:-$ROOT_DIR/deploy/compose/docker-compose.prod.yml}"
COMPOSE_ENV_FILE="${AJENDA_PROOF_COMPOSE_ENV_FILE:-$ROOT_DIR/deploy/compose/.env.prod}"

log() {
  printf '[sync-frontend-env] %s\n' "$*"
}

mkdir -p "$(dirname "$MASTER_FILE")"

if [[ -f "$MASTER_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$MASTER_FILE"
fi

if [[ -z "${AJENDA_DEV_API_KEY:-}" ]]; then
  log "creating persistent dev API key for tenant $TENANT_ID"
  read -r KEY_ID PLAINTEXT < <(
    docker compose -p compose --env-file "$COMPOSE_ENV_FILE" -f "$COMPOSE_FILE" exec -T api python - <<PY
from backend.app.config import get_settings
from backend.db.session import DatabaseRuntime
from backend.services.api_key_service import ApiKeyService

tenant_id = "${TENANT_ID}"
runtime = DatabaseRuntime(get_settings())
with runtime.session_context() as session:
    plaintext, record = ApiKeyService(session=session).create_key(
        tenant_id=tenant_id,
        scopes=("execution:view", "execution:queue"),
        roles=("tenant_admin",),
        purpose="operational",
    )
    session.commit()
    print(record.key_id, plaintext)
runtime.dispose()
PY
  )
  AJENDA_DEV_API_KEY="${KEY_ID}.${PLAINTEXT}"
  cat >"$MASTER_FILE" <<EOF
# Ajenda local frontend preload — never commit
export AJENDA_DEV_TENANT_ID='${TENANT_ID}'
export AJENDA_DEV_API_KEY='${AJENDA_DEV_API_KEY}'
EOF
  chmod 600 "$MASTER_FILE"
  log "saved master copy: $MASTER_FILE"
else
  log "reusing API key from $MASTER_FILE"
fi

cat >"$FRONTEND_ENV" <<EOF
# Generated by scripts/dev/sync-frontend-env.sh — never commit
VITE_API_BASE_URL=
VITE_DEFAULT_TENANT_ID=${AJENDA_DEV_TENANT_ID:-$TENANT_ID}
VITE_DEFAULT_API_KEY=${AJENDA_DEV_API_KEY}
EOF
chmod 600 "$FRONTEND_ENV"
log "wrote $FRONTEND_ENV"
log "restart Vite to pick up env: cd frontend && npm run dev"